TOP_LIST_LENGTH = 10;


KEYWORD_PREF_MULTIPLIER = 10;
AUTHOR_PREF_MULTIPLIER = 6;
SOURCE_PREF_MULTIPLIER = 4;

KEYWORD_HOT_MULTIPLIER = 3;
SOURCE_HOT_MULTIPLIER = 2;

ARTICLE_BODY  = "article_body";
ARTICLE_TITLE = "article_title";
ARTICLE_SOURCE = "article_source";
ARTICLE_AUTHOR = "article_author";
ARTICLE_TOPICS = "article_topics";
